package models;

import mon_calc.entity.Move;
import mon_calc.ds.Nature;
import mon_calc.entity.EStat;
import mon_calc.entity.Ability;
import mon_calc.entity.Item;
import mon_calc.entity.MonType;
import mon_calc.entity.Mon;
import models.ModelMon;

class ModelMonManager extends models.autogenerated.ModelMonManager {

	public function getByMon(
		oMon :Mon
	) :ModelMon {

		var mParam = [
			'type' => oMon.getType().getId(),
			'ev_hp' => oMon.getStatTrain( Health ),
			'ev_att' => oMon.getStatTrain( Att ),
			'ev_def' => oMon.getStatTrain( Def ),
			'ev_mag' => oMon.getStatTrain( Mag ),
			'ev_res' => oMon.getStatTrain( Res ),
			'ev_speed' => oMon.getStatTrain( Speed ),
			'ability' => oMon.getType().getAbilityAr().indexOf( oMon.getAbility() ),
			'item' => orm.modelItem.getItemId( oMon.getItem() ),
			'level' => oMon.getLevel(),
			'nature' => oMon.getNature().getId(),
			'move_0' => orm.modelMove.getModelMoveId( oMon.getMove( 0 ) ),
			'move_1' => orm.modelMove.getModelMoveId( oMon.getMove( 1 ) ),
			'move_2' => orm.modelMove.getModelMoveId( oMon.getMove( 2 ) ),
			'move_3' => orm.modelMove.getModelMoveId( oMon.getMove( 3 ) ),
		];
		var a = [];
		for( k => v in mParam )
			a.push( '`'+ k + '` = ' + db.quote(v) );
		var o = getBySqlOne('SELECT * FROM model_mon WHERE ' + a.join(' AND ') );
		if( o != null ) return o;
		return create( 
			oMon.getType().getId(),
			oMon.getStatTrain( Health ),
			oMon.getStatTrain( Att ),
			oMon.getStatTrain( Def ),
			oMon.getStatTrain( Mag ),
			oMon.getStatTrain( Res ),
			oMon.getStatTrain( Speed ),
			oMon.getType().getAbilityAr().indexOf( oMon.getAbility() ),
			orm.modelItem.getItemId( oMon.getItem() ),
			oMon.getLevel(),
			oMon.getNature().getId(),
			orm.modelMove.getModelMoveId( oMon.getMove( 0 ) ),
			orm.modelMove.getModelMoveId( oMon.getMove( 1 ) ),
			orm.modelMove.getModelMoveId( oMon.getMove( 2 ) ),
			orm.modelMove.getModelMoveId( oMon.getMove( 3 ) )
		);
	}
}