package models;

import mon_calc.entity.Move;
import models.ModelMove;

class ModelMoveManager extends models.autogenerated.ModelMoveManager {
	public function getModelMoveId( oMove :Move ) :Null<Int> {
		if( oMove == null ) return null;

		var o = getBySqlOne( 'SELECT * FROM model_move WHERE `key` = ' + db.quote(oMove.getId()) );
		if( o == null ) {
			o = create( oMove.getId() );
		}
		return o.id;
	}
}