package models;

import mon_calc.entity.Item;
import models.ModelItem;

class ModelItemManager extends models.autogenerated.ModelItemManager {
	public function getItemId( oItem :Item ) :Null<Int> {
		if( oItem == null ) return 1;

		var o = getBySqlOne( 'SELECT * FROM model_item WHERE `key` = ' + db.quote(oItem.getKey()) );
		if( o == null ) {
			o = create( oItem.getKey() );
		}
		return o.id;
	}
}