// This is autogenerated file. Do not edit!

package models.autogenerated;

class ModelAbilityManager
{
	var db : orm.Db;
	var orm : models.Orm;
	public var query(get, never) : orm.SqlQuery<models.ModelAbility>;

	function get_query() : orm.SqlQuery<models.ModelAbility>
	{
		return new orm.SqlQuery<models.ModelAbility>("model_ability", db, this);
	}

	public function new(db:orm.Db, orm:models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	function newModelFromParams(id:Int, key:String) : models.ModelAbility
	{
		var _obj = new models.ModelAbility(db, orm);
		_obj.id = id;
		_obj.key = key;
		return _obj;
	}

	function newModelFromRow(d:Dynamic) : models.ModelAbility
	{
		var _obj = new models.ModelAbility(db, orm);
		_obj.id = Reflect.field(d, 'id');
		_obj.key = Reflect.field(d, 'key');
		return _obj;
	}

	public function where(field:String, op:String, value:Dynamic) : orm.SqlQuery<models.ModelAbility>
	{
		return query.where(field, op, value);
	}

	public function get(id:Int) : models.ModelAbility
	{
		return getBySqlOne('SELECT * FROM `model_ability` WHERE `id` = ' + db.quote(id));
	}

	public function create(key:String) : models.ModelAbility
	{
		db.query('INSERT INTO `model_ability`(`key`) VALUES (' + db.quote(key) + ')');
		return newModelFromParams(db.lastInsertId(), key);
	}

	public function createNamed(data:{ key:String }) : models.ModelAbility
	{
		db.query('INSERT INTO `model_ability`(`key`) VALUES (' + db.quote(data.key) + ')');
		return newModelFromParams(db.lastInsertId(), data.key);
	}

	public function createOptional(data:{ ?key:String }) : models.ModelAbility
	{
		createOptionalNoReturn(data);
		return get(db.lastInsertId());
	}

	public function createOptionalNoReturn(data:{ ?key:String }) : Void
	{
		var fields = [];
		var values = [];
		if (Reflect.hasField(data, 'key')) { fields.push('`key`'); values.push(db.quote(data.key)); }
		db.query('INSERT INTO `model_ability`(' + fields.join(", ") + ') VALUES (' + values.join(", ") + ')');
	}

	public function delete(id:Int) : Void
	{
		db.query('DELETE FROM `model_ability` WHERE `id` = ' + db.quote(id) + ' LIMIT 1');
	}

	public function getAll(_order:String=null) : Array<models.ModelAbility>
	{
		return getBySqlMany('SELECT * FROM `model_ability`' + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function getBySqlOne(sql:String) : models.ModelAbility
	{
		var rows = db.query(sql + ' LIMIT 1');
		if (rows.length == 0) return null;
		return newModelFromRow(rows.next());
	}

	public function getBySqlMany(sql:String) : Array<models.ModelAbility>
	{
		var rows = db.query(sql);
		var list : Array<models.ModelAbility> = [];
		for (row in rows)
		{
			list.push(newModelFromRow(row));
		}
		return list;
	}
}