// This is autogenerated file. Do not edit!

package models.autogenerated;

class Orm
{
	public var modelAbility(default, null) : models.ModelAbilityManager;
	public var modelItem(default, null) : models.ModelItemManager;
	public var modelMon(default, null) : models.ModelMonManager;
	public var modelMove(default, null) : models.ModelMoveManager;

	public function new(db:orm.Db) : Void
	{
		this.modelAbility = new models.ModelAbilityManager(db, cast this);
		this.modelItem = new models.ModelItemManager(db, cast this);
		this.modelMon = new models.ModelMonManager(db, cast this);
		this.modelMove = new models.ModelMoveManager(db, cast this);
	}
}